package polimi.awt.twitter.entity;

// default package
// Generated Jun 10, 2013 6:37:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tweet generated by hbm2java
 */
@Entity
@Table(name = "Tweet", catalog = "DBawtTwitter")
public class Tweet implements java.io.Serializable {

	private Integer idTweet;
	private Que que;
	private Date date;
	private int day;
	private int hour;
	private int minute;
	private int month;
	private String tweetText;
	private int year;
	private String author;
	private String geoLocation;

	public Tweet() {
	}

	public Tweet(Que que, Date date, int day, int hour, int minute, int month,
			int year, String author) {
		this.que = que;
		this.date = date;
		this.day = day;
		this.hour = hour;
		this.minute = minute;
		this.month = month;
		this.year = year;
		this.author = author;
	}

	public Tweet(Que que, Date date, int day, int hour, int minute, int month,
			String tweetText, int year, String author, String geoLocation) {
		this.que = que;
		this.date = date;
		this.day = day;
		this.hour = hour;
		this.minute = minute;
		this.month = month;
		this.tweetText = tweetText;
		this.year = year;
		this.author = author;
		this.geoLocation = geoLocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTweet", unique = true, nullable = false)
	public Integer getIdTweet() {
		return this.idTweet;
	}

	public void setIdTweet(Integer idTweet) {
		this.idTweet = idTweet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idQue", nullable = false)
	public Que getQue() {
		return this.que;
	}

	public void setQue(Que que) {
		this.que = que;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Day", nullable = false)
	public int getDay() {
		return this.day;
	}

	public void setDay(int day) {
		this.day = day;
	}

	@Column(name = "Hour", nullable = false)
	public int getHour() {
		return this.hour;
	}

	public void setHour(int hour) {
		this.hour = hour;
	}

	@Column(name = "Minute", nullable = false)
	public int getMinute() {
		return this.minute;
	}

	public void setMinute(int minute) {
		this.minute = minute;
	}

	@Column(name = "Month", nullable = false)
	public int getMonth() {
		return this.month;
	}

	public void setMonth(int month) {
		this.month = month;
	}

	@Column(name = "TweetText", length = 45)
	public String getTweetText() {
		return this.tweetText;
	}

	public void setTweetText(String tweetText) {
		this.tweetText = tweetText;
	}

	@Column(name = "Year", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "author", nullable = false, length = 45)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "geoLocation", length = 45)
	public String getGeoLocation() {
		return this.geoLocation;
	}

	public void setGeoLocation(String geoLocation) {
		this.geoLocation = geoLocation;
	}

}
